@extends('layouts.app')

@section('content')

<br /><br /><br /><br /><br /><br />

<p style='margin: 0in 0in 15pt; line-height: 150%; font-size: 15px; font-family: "Calibri", sans-serif; text-align: left; background: white none repeat scroll 0% 0%;'><span style='font-size:14px;line-height:150%;font-family:"Arial",sans-serif;color:black;'>This agreement is written to govern the terms of usage of this site, between &lsquo;the User&rdquo; and alstomfx.com. The User is bound to abide by the conditions and the terms listed below. Particularly, those terms that apply to alstomfx.com third payment system as well as any other services offered on alstormfx.com.</span></p>
<p style='margin: 0in 0in 11.25pt; line-height: 150%; font-size: 15px; font-family: "Calibri", sans-serif; text-align: left; background: white none repeat scroll 0% 0%;'><strong><span style='font-size:18px;line-height:150%;font-family:"Arial",sans-serif;color:black;'>REGULATIONS</span></strong></p>
<p style='margin: 0in 0in 15pt; line-height: 150%; font-size: 15px; font-family: "Calibri", sans-serif; text-align: left; background: white none repeat scroll 0% 0%;'><span style='font-size:14px;line-height:150%;font-family:"Arial",sans-serif;color:black;'>Without permission, alstomfx.com reserves its rights to change this Agreement by making updates to the terms and conditions. Any upcoming changes will be posted via the User&rsquo;s account on their notification page. Changes posted will be effective after 30 days of the original posting date, unless noted otherwise. To maintain access to alstormfx.com, the user will abide by any updates from future changes.</span></p>
<p style='margin: 0in 0in 11.25pt; line-height: normal; font-size: 15px; font-family: "Calibri", sans-serif; background: white none repeat scroll 0% 0%; text-align: left;'><strong><span style='font-size:18px;font-family:"Arial",sans-serif;color:black;'>GENERAL PROVISIONS</span></strong></p>
<ul class="decimal_type" style="list-style-type: disc;margin-left:1.25px;">
    <li style="text-align: left;"><span style='font-family:"Arial",sans-serif;font-size:10.5pt;color:black;'>1.1 In strict compliance to these provisions, alstormfx.com will take on the responsibility of providing the aforementioned services to its investors.</span></li>
    <li style="text-align: left;"><span style='font-family:"Arial",sans-serif;font-size:10.5pt;color:black;'>1.2. Upon agreeing to these written terms and conditions of alstormfx.com, user access is granted to the site.</span></li>
</ul>
<p style='margin: 0in; line-height: normal; font-size: 15px; font-family: "Calibri", sans-serif; background: white none repeat scroll 0% 0%; text-align: left;'><span style='font-size:14px;font-family:"Arial",sans-serif;color:black;'>To abide by all of the internal rules, the user has to be knowledgeable of their obligations and responsibilities to the company. These obligations are stated in the provisions provided below.</span></p>
<ul class="decimal_type" style="list-style-type: disc;margin-left:1.25px;">
    <li style="text-align: left;"><span style='font-family:"Arial",sans-serif;font-size:10.5pt;color:black;'>1.3. In case of violations by the user, particularly one paragraph of these provisions, the company disclaims any and all liability to the user.</span></li>
    <li style="text-align: left;"><span style='font-family:"Arial",sans-serif;font-size:10.5pt;color:black;'>1.4. At any time, without any update of notice, alstormfx.com reserves the right to publish updates.</span></li>
    <li style="text-align: left;"><span style='font-family:"Arial",sans-serif;font-size:10.5pt;color:black;'>1.5 The user acknowledges, in advance, that any operations performed on this site is done at their own risk unless provided in any related company documents or specified in the above provisions. Additionally, previous performance on the site does not guarantee the same performance in future activities. The company also has the right to utilize the user&rsquo;s voluntary funds for consultation purposes and will have control over the time frame in which the funds will be used.</span></li>
</ul>
<p style='margin: 0in 0in 11.25pt; line-height: normal; font-size: 15px; font-family: "Calibri", sans-serif; background: white none repeat scroll 0% 0%; text-align: left;'><strong><span style='font-size:18px;font-family:"Arial",sans-serif;color:black;'>PARTIES OF THE AGREEMENT</span></strong></p>
<ul class="decimal_type" style="list-style-type: disc;margin-left:1.25px;">
    <li style="text-align: left;"><span style='font-family:"Arial",sans-serif;font-size:10.5pt;color:black;'>2.1 alstormfx.com (presently called the performer), under this agreement, will provide users specified services, which includes major investment funds of the company in the area of money management consulting.</span></li>
    <li style="text-align: left;"><span style='font-family:"Arial",sans-serif;font-size:10.5pt;color:black;'>2.2 After the user opens up a service account with alstomfx.com, they will automatically become a party of this agreement and also adhere to follow the aforementioned provisions.</span></li>
    <li style="text-align: left;"><span style='font-family:"Arial",sans-serif;font-size:10.5pt;color:black;'>2.3 To open up a service account, the user must be at least 18 years of age or meet the legal age requirements in their own country.</span></li>
    <li style="text-align: left;"><span style='font-family:"Arial",sans-serif;font-size:10.5pt;color:black;'>2.4 Company is not liable for unreliable, inaccurate or incomplete information provided by the Internet user. Particularly, in the cases where financial transactions made are improper.</span></li>
    <li style="text-align: left;"><span style='font-family:"Arial",sans-serif;font-size:10.5pt;color:black;'>2.5 The user is forbidden to use the company services for any illegal purposes including money acquiring illegal income and money laundering.</span></li>
    <li style="text-align: left;"><span style='font-family:"Arial",sans-serif;font-size:10.5pt;color:black;'>2.6 To improve the quality of the company&rsquo;s services offered, the user will agree to all correspondences and communications being recorded.</span></li>
    <li style="text-align: left;"><span style='font-family:"Arial",sans-serif;font-size:10.5pt;color:black;'>2.7 Under the conditions of protecting privacy, the Company will comply with not releasing any of the user&rsquo;s personal data.</span></li>
</ul>
<p style='margin: 0in 0in 11.25pt; line-height: normal; font-size: 15px; font-family: "Calibri", sans-serif; background: white none repeat scroll 0% 0%; text-align: left;'><strong><span style='font-size:18px;font-family:"Arial",sans-serif;color:black;'>ACCOUNT USE REGULATIONS</span></strong></p>
<ul class="decimal_type" style="list-style-type: disc;margin-left:1.25px;">
    <li style="text-align: left;"><span style='font-family:"Arial",sans-serif;font-size:10.5pt;color:black;'>3.1 To prevent the Internet user from creating the illusion of partnership with the company for affiliate reward purposes, the Company reserves the right of determining how many accounts can be registered under the same name.</span></li>
    <li style="text-align: left;"><span style='font-family:"Arial",sans-serif;font-size:10.5pt;color:black;'>3.2 The rights to use an account is not transferrable so reassignment is prohibited.</span></li>
    <li style="text-align: left;"><span style='font-family:"Arial",sans-serif;font-size:10.5pt;color:black;'>3.3 All users are pre-warned that password access or any other user account information will not be granted to any member of the administration or its specialists.</span></li>
    <li style="text-align: left;"><span style='font-family:"Arial",sans-serif;font-size:10.5pt;color:black;'>3.4. Without prior notice to the company&rsquo;s administration, the user has the right to modify their personal data and payment information. In order to prevent fraudulent activities, however, in situations where payment details have changed, the company and their admin reserves the right to withhold user payment for a period of no longer than 3 days.</span></li>
    <li style="text-align: left;"><span style='font-family:"Arial",sans-serif;font-size:10.5pt;color:black;'>3.5 In cases where the account password has been lost, the user can request the password for free and it will be sent by email.</span></li>
    <li style="text-align: left;"><span style='font-family:"Arial",sans-serif;font-size:10.5pt;color:black;'>3.6 In order to eliminate problems with hackers, the user must adhere to utilizing computer protection software (i.e. firewall protection and antivirus applications).</span></li>
    <li style="text-align: left;"><span style='font-family:"Arial",sans-serif;font-size:10.5pt;color:black;'>3.7 The user will not be provided with the capability to delete his or her account.</span></li>
</ul>
<p style='margin: 0in 0in 11.25pt; line-height: normal; font-size: 15px; font-family: "Calibri", sans-serif; background: white none repeat scroll 0% 0%; text-align: left;'><strong><span style='font-size:18px;font-family:"Arial",sans-serif;color:black;'>INVESTMENT TERMS AND CONDITIONS</span></strong></p>
<ul class="decimal_type" style="list-style-type: disc;margin-left:1.25px;">
    <li style="text-align: left;"><span style='font-family:"Arial",sans-serif;font-size:10.5pt;color:black;'>4.1 The investment plan that the user chooses to participate in will determine all earnings accurate base.</span></li>
    <li style="text-align: left;"><span style='font-family:"Arial",sans-serif;font-size:10.5pt;color:black;'>4.2 All users will receive their percentage of profit on a timely basis (excluding Saturdays and Sundays).</span></li>
    <li style="text-align: left;"><span style='font-family:"Arial",sans-serif;font-size:10.5pt;color:black;'>4.3 Profit can be withdrawn by the user via his or her bank details or other e-wallets provided.</span></li>
    <li style="text-align: left;"><span style='font-family:"Arial",sans-serif;font-size:10.5pt;color:black;'>4.4 After a withdrawal profit request has been received and approved by the company, the transactions are processed and users gets their payments within 24 hours.</span></li>
    <li style="text-align: left;"><span style='font-family:"Arial",sans-serif;font-size:10.5pt;color:black;'>4.5 In case transactions from the user&apos;s wallet occurs, the company is not liable for either deposit or withdrawal operations.</span></li>
</ul>
<p style='margin: 0in 0in 11.25pt; line-height: normal; font-size: 15px; font-family: "Calibri", sans-serif; background: white none repeat scroll 0% 0%; text-align: left;'><strong><span style='font-size:18px;font-family:"Arial",sans-serif;color:black;'>&nbsp;</span></strong></p>
<p style='margin: 0in 0in 11.25pt; line-height: normal; font-size: 15px; font-family: "Calibri", sans-serif; background: white none repeat scroll 0% 0%; text-align: left;'><strong><span style='font-size:18px;font-family:"Arial",sans-serif;color:black;'>risk disclosure</span></strong></p>
<ul class="decimal_type" style="list-style-type: disc;margin-left:1.25px;">
    <li style="text-align: left;"><span style='font-family:"Arial",sans-serif;font-size:10.5pt;color:black;'>5.1 Users participation is completely at their own risks. Similar to any other local bank or financial institution, investments have their own inherent risks and advantages. The user can remain anonymous with their investments and expected to receive higher returns when compared to the traditional financial institutions. Therefore, any and all risks are the complete responsibility of the users that join as a member.</span></li>
    <li style="text-align: left;"><span style='font-family:"Arial",sans-serif;color:black;'>5.2&nbsp;</span><span style='font-family:"Arial",sans-serif;color:black;'>In consideration of alstormfx.com agreeing to enter into over-the-counter (&quot;OTC&quot;) contracts for differences (&quot;CFDs&quot;) and foreign exchange contracts (&quot;FX Contracts&quot;) with the user, User acknowledges, understands and agrees that:<br>&nbsp;Trading CFDs and FX Contracts is highly speculative, involves a significant risk of loss and is&nbsp;</span><span style='font-family:"Arial",sans-serif;color:black;'>not suitable for all investors but only for those customers who&nbsp;</span><span style='font-family:"Arial",sans-serif;font-size:10.5pt;color:black;'>understand and are willing to assume the economic, legal and other risks involved; are experienced and knowledgeable about trading in derivatives and in underlying asset types; and are financially able to assume losses significantly in excess of margin or deposits because investors may lose the total value of the contract not just the margin or the deposit.<br>&nbsp;Neither CFDs nor FX Contracts are appropriate investments for retirement funds. CFD and FX transactions are among the riskiest types of investments and can result in large losses. Customer represents, warrants and agrees that Customer understands these risks, is willing and able, financially and otherwise, to assume the risks of trading CFDs and FX Contracts and that the loss of Customer&apos;s entire account balance will not change Customer&apos;s life</span><span style='font-family:"Arial",sans-serif;'>style.</span></li>
</ul>
<p style='margin: 0in 0in 11.25pt; line-height: normal; font-size: 15px; font-family: "Calibri", sans-serif; background: white none repeat scroll 0% 0%; text-align: left;'><strong><span style='font-size:18px;font-family:"Arial",sans-serif;color:black;'>&nbsp;</span></strong></p>
<p style='margin: 0in 0in 11.25pt; line-height: normal; font-size: 15px; font-family: "Calibri", sans-serif; background: white none repeat scroll 0% 0%; text-align: left;'><strong><span style='font-size:18px;font-family:"Arial",sans-serif;color:black;'>FORCE MAJOR CIRCUMSTANCES</span></strong></p>
<div style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>
    <ul style="margin-bottom:0in;list-style-type: disc;margin-left:1.25px;">
        <li style='margin: 0in 0in 8pt; line-height: 107%; font-size: 15px; font-family: "Calibri", sans-serif; text-align: left;'><span style='font-family:"Arial",sans-serif;font-size:10.5pt;color:black;'>6.1 In the case of a natural disaster (i.e. wars, man-made disasters, earthquakes, revolutions, epidemics, global economic crisis, strikes), the company reserves the right to stop its operations and any associated obligations. If the site is suspended due to any of these natural disasters, the company will notify the users of such. The company is not liable for any activity beyond its control including, fraudulent activity or illegal hacking of the user&rsquo;s account.</span></li>
    </ul>
</div>
@endsection





